import {
  course1,
  course2,
  course3,
  course4,
  course5,
  course6,
  course7,
  course8,
  avatar,
  category1,
  category2,
  category3,
  category4,
  category5,
  category6,
  category7,
  category8,
  instructor1,
  instructor2,
  instructor3,
  instructor4,
  student1,
  student2,
  student3,
  student4,
  cta1,
  cta2,
  cta3,
  cta4,
} from "../assets/export";
import { FaStar } from "react-icons/fa6";

export const buttonsData = [
  {
    id: 1,
    name: "All",
  },
  {
    id: 2,
    name: "Trending",
  },
  {
    id: 3,
    name: "Popular",
  },
  {
    id: 4,
    name: "Featured",
  },
];

export const sliderSettings = {
  slidesPerView: 1,
  spaceBetween: 20,
  breakpoints: {
    300: {
      slidesPerView: 1,
    },
    768: {
      slidesPerView: 2,
    },
    1024: {
      slidesPerView: 3,
    },
    1100: {
      slidesPerView: 4,
    },
  },
};

export const coursesData = [
  {
    id: 1,
    img: course1,
    icon: <FaStar size={11} />,
    title: "Learn Figma - UI/UX Design Essential Training",
    lesson: "6 lessons",
    duration: "3h 56m",
    level: "Beginner",
    avatar: avatar,
    name: "Ali Tufan",
    oldPrice: 179,
    newPrice: 79,
  },
  {
    id: 2,
    img: course2,
    icon: <FaStar size={11} />,
    title: "Complete Python Bootcamp From Zero TO Hero in Python",
    lesson: "6 lessons",
    duration: "3h 56m",
    level: "Beginner",
    avatar: avatar,
    name: "Ali Tufan",
    oldPrice: 179,
    newPrice: 79,
  },
  {
    id: 3,
    img: course3,
    icon: <FaStar size={11} />,
    title: "Angular - The Complete Guide (2024 Edition)",
    lesson: "6 lessons",
    duration: "3h 56m",
    level: "Beginner",
    avatar: avatar,
    name: "Ali Tufan",
    oldPrice: 179,
    newPrice: 79,
  },
  {
    id: 4,
    img: course4,
    icon: <FaStar size={11} />,
    title: "The Ultimate Drawing Course Beginner To Advanced",
    lesson: "6 lessons",
    duration: "3h 56m",
    level: "Beginner",
    avatar: avatar,
    name: "Ali Tufan",
    oldPrice: 179,
    newPrice: 79,
  },
  {
    id: 5,
    img: course5,
    icon: <FaStar size={11} />,
    title: "Photography Masterclass: A Complete Guide To Photography",
    lesson: "6 lessons",
    duration: "3h 56m",
    level: "Beginner",
    avatar: avatar,
    name: "Ali Tufan",
    oldPrice: 179,
    newPrice: 79,
  },
  {
    id: 6,
    img: course6,
    icon: <FaStar size={11} />,
    title: "Instagram 2024: Complete Guide To Instagram",
    lesson: "6 lessons",
    duration: "3h 56m",
    level: "Beginner",
    avatar: avatar,
    name: "Ali Tufan",
    oldPrice: 179,
    newPrice: 79,
  },
  {
    id: 7,
    img: course7,
    icon: <FaStar size={11} />,
    title: "Complete Blender Creator: Learn 3D Modelling For Beginners",
    lesson: "6 lessons",
    duration: "3h 56m",
    level: "Beginner",
    avatar: avatar,
    name: "Ali Tufan",
    oldPrice: 179,
    newPrice: 79,
  },
  {
    id: 8,
    img: course8,
    icon: <FaStar size={11} />,
    title: "The Complete Financial Analyst Training & Investing Course ",
    lesson: "6 lessons",
    duration: "3h 56m",
    level: "Beginner",
    avatar: avatar,
    name: "Ali Tufan",
    oldPrice: 179,
    newPrice: 79,
  },
];

export const categoriesData = [
  {
    id: 1,
    img: category1,
    title: "Digital Marketing",
    amount: 573,
  },
  {
    id: 2,
    img: category2,
    title: "Web Development",
    amount: 573,
  },
  {
    id: 3,
    img: category3,
    title: "Graphic Design",
    amount: 573,
  },
  {
    id: 4,
    img: category4,
    title: "Social Sciences",
    amount: 573,
  },
  {
    id: 5,
    img: category5,
    title: "Photography",
    amount: 573,
  },
  {
    id: 6,
    img: category6,
    title: "Art & Humanities",
    amount: 573,
  },
  {
    id: 7,
    img: category7,
    title: "Personal Development",
    amount: 573,
  },
  {
    id: 8,
    img: category8,
    title: "IT and Software",
    amount: 573,
  },
];

export const instructorsData = [
  {
    id: 1,
    img: instructor1,
    name: "Flyod Miles",
    job: "President of Sales",
    icon: <FaStar size={11} />,
    course: 15,
    student: 692,
  },
  {
    id: 2,
    img: instructor2,
    name: "Cameron Williamson",
    job: "Web Designer",
    icon: <FaStar size={11} />,
    course: 15,
    student: 692,
  },
  {
    id: 3,
    img: instructor3,
    name: "Brooklyn Simmons",
    job: "Dog Trainer",
    icon: <FaStar size={11} />,
    course: 15,
    student: 692,
  },
  {
    id: 4,
    img: instructor4,
    name: "Wade Warren",
    job: "Marketing Coordinator",
    icon: <FaStar size={11} />,
    course: 15,
    student: 692,
  },
];

export const studentsData = [
  {
    id: 1,
    img: student1,
    name: "Brooklyn Simmons",
    job: "Web Designer",
  },
  {
    id: 2,
    img: student2,
    name: "Cody Fisher",
    job: "Dog Trainer",
  },
  {
    id: 3,
    img: student3,
    name: "Marvin McKinney",
    job: "President of Sales",
  },
  {
    id: 4,
    img: student4,
    name: "Jane Cooper",
    job: "Marketing Coordinator",
  },
];

export const ctaData = [
  {
    id: 1,
    img: cta1,
    title: "Learn with Experts",
    desc: "Grursus mal suada faci lisis that ipsum ameti consecte.",
  },
  {
    id: 2,
    img: cta2,
    title: "Learn Anything",
    desc: "Grursus mal suada faci lisis that ipsum ameti consecte.",
  },
  {
    id: 3,
    img: cta3,
    title: "Flexible Learning",
    desc: "Grursus mal suada faci lisis that ipsum ameti consecte.",
  },
  {
    id: 4,
    img: cta4,
    title: "Industrial Standard",
    desc: "Grursus mal suada faci lisis that ipsum ameti consecte.",
  },
];
